### ISSUE TITLE
At Your Knuckle Tips Description Suggestion

### ISSUE THREAD

**Issue by SamaraIsnt** [SamaraIsnt/RADRevampProject#279]
Maybe add in the description that these potion rings use experience to stay active. There is a handful of people who asked why their experience was disappearing.

**Comment by Zarchyar** [comment]
Could also just add a tooltip like this to it simple one line in a craft tweeker script in this case can even change the text color if we wanted to. following line is the one used to add this tool tip.

<<extraalchemy:potion_ring>>.addTooltip("Passively consumes xp to grant the potion effect.");

![image](https://user-images.githubusercontent.com/72223492/174483266-2d2537b8-eb5f-41ba-930f-0e9d2fc8556c.png)
