### ISSUE TITLE
Prince Charming Charm Belt Item Not Completing Quest

### ISSUE THREAD

**Issue by SamaraIsnt** [SamaraIsnt/RADRevampProject#287]
I've added in a Charm Belt from the JEI and its not counting it unlike all of the other charms.

**Comment by Mastarin** [comment]
I may have put all the charms into the belt and made it NBT Match meaning you'd need to craft all charms and put them into the belt to complete the quest. Changed to just crafting all charms. Removed Charm Belt from the quest.
