### ISSUE TITLE
Wither Pet Causing Random Deaths

### ISSUE THREAD

**Issue by SamaraIsnt** [SamaraIsnt/RADRevampProject#288]
We had a few reports of Wither Pets from the Inventory Pets mods randomly killing people.
Discord discussion about it: https://discord.com/channels/512339624627011586/512340728215502878/970015021243445308
Video 1: Uploading unknown_replay_2022.04.29-12.32_Trim.mp4…
Video 2: https://youtu.be/hl-6GeTw5po

**Comment by DoctorMage** [comment]
added a warning in #381
