### ISSUE TITLE
Broken quest verdant heart charm

### ISSUE THREAD

**Issue by TheFlame52** [SamaraIsnt/RADRevampProject#292]
Verdant heart charm quest detects any version of the charm, when it's clear that both activated versions are intended to be required

**Comment by SamaraIsnt** [comment]
Also missing the third type of Heart Charm (the one that pulses green).

**Comment by TheFlame52** [comment]
There's three types of verdant heart charm. The unspecialized one that just cures negative potion effects, the one that regenerates health, and the one that provides hunger and breath. The last two retain the same effect as the first.
