### ISSUE TITLE
Move the Auxiliary Slurry Pump to be a Dependency of Essentia Smeltery

### ISSUE THREAD

**Issue by SamaraIsnt** [SamaraIsnt/RADRevampProject#295]
The Essentia Smeltery uses both the Auxiliary Slurry Pump and Auxiliary Venting Port with no correlation to pipes. In addition, it would be best to add the Arcane Alembic, too, since its an essential part to the Essentia Smeltery.

**Comment by dr3ams** [comment]
+

**Comment by SamaraIsnt** [comment]
Forgot to mark this as completed
![image](https://user-images.githubusercontent.com/104589186/180347194-21a3339c-68ec-46a5-8482-d008b189b314.png)
