### ISSUE TITLE
Move or Remove Arcane Bellows Quest in Favor for Issue #295

### ISSUE THREAD

**Issue by SamaraIsnt** [SamaraIsnt/RADRevampProject#296]
Arcane Bellows cannot be used with the Infernal Furnace. Issue #295

**Comment by dr3ams** [comment]
+

**Comment by SamaraIsnt** [comment]
![image](https://user-images.githubusercontent.com/104589186/180346906-77d6b793-bca1-40ff-931d-4a55c89319c5.png)
forgot to mark this as completed.
Resolves #295 as well
