### ISSUE TITLE
random universal wizard artefact reward bug in Feels a Bit Sheer Quest

### ISSUE THREAD

**Issue by Alucabr** [SamaraIsnt/RADRevampProject#299]
random universal wizard artefact reward bug in quest This Feels A Bit Sheer, just the random universal wizard artefact reward didn't give me anything, the money and exp did.

**Comment by SamaraIsnt** [comment]
I checked the reward in the ftbquest editor and there is nothing inside of that reward table.
![image](https://user-images.githubusercontent.com/104589186/174493975-8684c055-e43a-44c8-b1e6-e84ca7564b61.png)
