### ISSUE TITLE
Catch em all 

### ISSUE THREAD

**Issue by DoctorMage** [SamaraIsnt/RADRevampProject#305]
The quest catch them all is not registering fish caught

![image](https://user-images.githubusercontent.com/85318453/174916040-c8c785aa-e14f-4a8e-8bf8-65e07d70ed4e.png)
Found by Sombrera#5641

**Comment by SamaraIsnt** [comment]
Which RAD Version?

**Comment by SamaraIsnt** [comment]
![image](https://user-images.githubusercontent.com/104589186/174952694-c0b1caa8-a141-41e3-a9e8-a01ef202c8cc.png)
Just found out. Closed
