### ISSUE TITLE
HarvestCraft Water Trap Fishing Suggestion

### ISSUE THREAD

**Issue by SamaraIsnt** [SamaraIsnt/RADRevampProject#307]
Original comment by Bizzoula:

Vanilla Fishing rod also catches harvestcraft fish. Disabling this setting means HC fish are only in Water Trap, which might be good to do

>  #Enables catching of HarvestCraft fish using the normal fishing rod. [default: true]
>     B:enableHCFish=true
![image](https://user-images.githubusercontent.com/104589186/175646264-83877a07-7407-4a31-b02b-f40105ebb0a6.png)

---
Separating which fish are caught where would make it easier for players if they're looking for a specific mod's fish.

**Comment by dr3ams** [comment]
good point
