### ISSUE TITLE
Roots Fire Starter Causes Clientside Crash

### ISSUE THREAD

**Issue by SamaraIsnt** [SamaraIsnt/RADRevampProject#308]
RAD Version: 1.50
No added mods, brand new install, and launcher is GDLauncher.

Issue: Roots Fire Starter item causes crash.
[Video](https://www.youtube.com/watch?v=Crpd7NDx_28&ab_channel=Snam)
Crash Report
[crash-2022-06-24_16.07.23-client.txt](https://github.com/SamaraIsnt/Roguelike-Adventures-and-Dungeons/files/8980467/crash-2022-06-24_16.07.23-client.txt)

**Comment by DoctorMage** [comment]
added warning tooltip in #384
![image](https://user-images.githubusercontent.com/85318453/201713206-0c886481-b0bf-4e5a-8a54-47f855898d9c.png)
