### ISSUE TITLE
Suggestion for megaloot

### ISSUE THREAD

**Issue by DoctorMage** [SamaraIsnt/RADRevampProject#310]
Add megaloot shards in the shop
allows a less rng dependant way of getting them for repairing the gear or getting upgrade tokens.

**Comment by VanyaBaou** [comment]
The whole point of Megaloot is that it's rng heavy loot, personally think adding it to shop is a bad idea

**Comment by DoctorMage** [comment]
Yeah realized should be scrapped for now since i've seen people farming literal blocks of **redacted** in under a minute for repetable quest
