### ISSUE TITLE
Quest "Bug Buster" contain wrong item to complete

### ISSUE THREAD

**Issue by BlueRayser** [SamaraIsnt/RADRevampProject#332]
1. 1.50
2. Buggin' Out
3. Dragonfly Wing are not from Erebus mod, see screenshot, it has SAME texture with Betweenlands mod
![image](https://user-images.githubusercontent.com/29048535/178996590-c9fe4cf0-4faf-44d0-84fe-0a3568130afd.png)

**Comment by SamaraIsnt** [comment]
![image](https://user-images.githubusercontent.com/104589186/179558104-6326ffa1-aa3d-4f57-b13c-41001f08bc99.png)
In the selection menu for it, this is the only thing that shows.
We can remove it entirely if we're unable to get the correct version of that item
