### ISSUE TITLE
Crash: V-Tweaks Horse Glue Looting 

### ISSUE THREAD

**Issue by VanyaBaou** [SamaraIsnt/RADRevampProject#337]
Having looting 4 or higher while killing a horse crashes the game.

https://github.com/oitsjustjose/V-Tweaks/blob/2bd1e7a38c6b56756899dfb26fc27409c4ff28d4/src/main/java/com/oitsjustjose/vtweaks/event/mobtweaks/MobDropBuffs.java#L69

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at com.oitsjustjose.vtweaks.event.mobtweaks.MobDropBuffs.registerTweak(MobDropBuffs.java:69)

B:"Enable "glue" drops"=true
change to false

**Comment by dr3ams** [comment]
disabled
