### ISSUE TITLE
Suggestion: Quark Rune Crafting

### ISSUE THREAD

**Issue by VanyaBaou** [SamaraIsnt/RADRevampProject#340]
Add recipes for Quark's runes

White rune recipe:
![image](https://user-images.githubusercontent.com/97327658/180077255-0674af6a-d021-48cf-8ca1-0228d573c0e2.png)
Other runes: White Rune + dye

recipes.addShaped("quark_rune_white",<quark:rune:0> * 4, [
[<minecraft:glowstone_dust>, <ebwizardry:magic_crystal>, <minecraft:glowstone_dust>],
[<ebwizardry:magic_crystal>, <minecraft:quartz_block>, <ebwizardry:magic_crystal>],
[<minecraft:glowstone_dust>, <ebwizardry:magic_crystal>, <minecraft:glowstone_dust>]]);

recipes.addShapeless("quark_rune_orange", <quark:rune:1>, [<quark:rune:0>,<ore:dyeOrange>]);
recipes.addShapeless("quark_rune_magenta", <quark:rune:2>, [<quark:rune:0>,<ore:dyeMagenta>]);
recipes.addShapeless("quark_rune_lightblue", <quark:rune:3>, [<quark:rune:0>,<ore:dyeLightBlue>]);
recipes.addShapeless("quark_rune_yellow", <quark:rune:4>, [<quark:rune:0>,<ore:dyeYellow>]);
recipes.addShapeless("quark_rune_lime", <quark:rune:5>, [<quark:rune:0>,<ore:dyeLime>]);
recipes.addShapeless("quark_rune_pink", <quark:rune:6>, [<quark:rune:0>,<ore:dyePink>]);
recipes.addShapeless("quark_rune_gray", <quark:rune:7>, [<quark:rune:0>,<ore:dyeGray>]);
recipes.addShapeless("quark_rune_lightgray", <quark:rune:8>, [<quark:rune:0>,<ore:dyeLightGray>]);
recipes.addShapeless("quark_rune_cyan", <quark:rune:9>, [<quark:rune:0>,<ore:dyeCyan>]);
recipes.addShapeless("quark_rune_purple", <quark:rune:10>, [<quark:rune:0>,<ore:dyePurple>]);
recipes.addShapeless("quark_rune_blue", <quark:rune:11>, [<quark:rune:0>,<ore:dyeBlue>]);
recipes.addShapeless("quark_rune_brown", <quark:rune:12>, [<quark:rune:0>,<ore:dyeBrown>]);
recipes.addShapeless("quark_rune_green", <quark:rune:13>, [<quark:rune:0>,<ore:dyeGreen>]);
recipes.addShapeless("quark_rune_red", <quark:rune:14>, [<quark:rune:0>,<ore:dyeRed>]);
recipes.addShapeless("quark_rune_black", <quark:rune:15>, [<quark:rune:0>,<ore:dyeBlack>]);

**Comment by dr3ams** [comment]
added
