### ISSUE TITLE
Suggestion: Stack Sizes

### ISSUE THREAD

**Issue by VanyaBaou** [SamaraIsnt/RADRevampProject#347]
this was discussed before and was supposed to be added iirc
**stackSize.zs**

<randomloot:basic_case>.maxStackSize = 64;
<randomloot:golden_case>.maxStackSize = 64;
<randomloot:titan_case>.maxStackSize = 64;

<ebwizardry:ruined_spell_book>.maxStackSize = 64;
<ebwizardry:arcane_tome>.maxStackSize = 64;
<ebwizardry:purifying_elixir>.maxStackSize = 64;

**Comment by dr3ams** [comment]
Done for 1.52
