### ISSUE TITLE
Suggestion: Reforge Materials for Artefacts

### ISSUE THREAD

**Issue by VanyaBaou** [SamaraIsnt/RADRevampProject#349]
new artefacts from Ancient Spellcraft, TF Spellpack, Mo Spells
also uses 1 new oreDict for some artefact (**oreDict.zs**)
- val crystalAcid = <ore:crystalAcid>;
- crystalAcid.add(<ebwizardry:magic_crystal:3>, <ebwizardry:magic_crystal:5>);

[ancientspellcraft_artefact_reforge_materials.txt](https://github.com/SamaraIsnt/Roguelike-Adventures-and-Dungeons/files/9277585/ancientspellcraft_artefact_reforge_materials.txt)
[tfspellpack_artefact_reforge_materials.txt](https://github.com/SamaraIsnt/Roguelike-Adventures-and-Dungeons/files/9277586/tfspellpack_artefact_reforge_materials.txt)
[mospells_artefact_reforge_materials.txt](https://github.com/SamaraIsnt/Roguelike-Adventures-and-Dungeons/files/9277587/mospells_artefact_reforge_materials.txt)

**Comment by dr3ams** [comment]
Done for 1.52
