### ISSUE TITLE
Suggestion: CraftPresence

### ISSUE THREAD

**Issue by VanyaBaou** [SamaraIsnt/RADRevampProject#350]
Because **DiscordSuite** has been in the pack for a long time and does literally nothing, and I can't recall it ever working at any point in time
https://www.curseforge.com/minecraft/mc-mods/craftpresence

[craftpresence.properties.txt](https://github.com/SamaraIsnt/Roguelike-Adventures-and-Dungeons/files/9277593/craftpresence.properties.txt)

uses my discord rich presence app, every dimension that should have an icon does
you can very easily create your own app and use your own screenshots for icons and whatever
asset zip here (too big to upload): https://discord.com/channels/512339624627011586/795205763568107520/1004969039489142895

**Comment by dr3ams** [comment]
Done for 1.52
