### ISSUE TITLE
Suggestion: Add Missing Translations

### ISSUE THREAD

**Issue by VanyaBaou** [SamaraIsnt/RADRevampProject#354]
Resource zip containing:
- missing enchant descriptions
- jei description corrections
- missing villager names
- typo fixes for some small things
- missing entity display names
- other stuff, just sort through and decide whatever needs to be taken in

[resources.zip](https://github.com/SamaraIsnt/Roguelike-Adventures-and-Dungeons/files/9277607/resources.zip)

**Comment by dr3ams** [comment]
Done for 1.52
