### ISSUE TITLE
Suggestion: Remove Wizardry Fates

### ISSUE THREAD

**Issue by VanyaBaou** [SamaraIsnt/RADRevampProject#356]
It's basically useless and even if it were useful (feature wise) it wouldn't fit RAD's playstyle (locking things out completely)
For people new to it, all it seems to do is cause misunderstandings
Original intention _was_ to use it to lock things behind it, but that wasn't ever configured

See convo

![image](https://user-images.githubusercontent.com/97327658/183311629-de4fca8c-090d-469e-8874-a851d7593023.png)

**Comment by dr3ams** [comment]
Done for 1.52
