### ISSUE TITLE
Suggestion: Disable Cursed Earth

### ISSUE THREAD

**Issue by VanyaBaou** [SamaraIsnt/RADRevampProject#360]
mob farms are cringe 👎🤪
**\config\extrautils2.cfg**
- B:CursedEarth=true

**Comment by VanyaBaou** [comment]
if its disabled, people can blame me
but realize that blaming me means you used it and are therefore admitting you are cringe 😎

**Comment by SamaraIsnt** [comment]
We would need to figure out which demographic of people use cursed earth farms. Are they people who want exp, or are they people who want mob drops?

The party of people who would like exp would do quests or make an endermen farm. The other party would complain with no other easy way to get drops.
If the majority of people want exp, they'd make an endermen farm anyways. We cannot prevent that without removing an important block or mob from the base game.

From a broader view, RAD has been stated to be anti-automation. Yet if the person is spending the time to kill each batch of monsters by hand, is it automation? All other methods to automate killing have been removed.

**Comment by VanyaBaou** [comment]
drop of evil / cursed earth is just a braindead easy way to infinitely automatically spawn mobs, and takes very little effort to make farming automatic

questioning if "killing by hand" makes mob farms not automation is nonsense, anyone and most everyone who uses mob farms uses an autoclicker to "kill by hand". so thats completely pointless to bring up here

the only real use of it is for super fast and efficient mob farms
if you can tell me how it has a use _besides_ that i'd like to hear, otherwise no point to keeping it enabled

according to hawk (and most everyone i've seen talk about it as well) it is mostly for xp purposes
![image](https://user-images.githubusercontent.com/97327658/183789824-e47355d7-6e1d-4b4d-8642-c2092cda99d7.png)

**Comment by SamaraIsnt** [comment]
Although endermen farms aren't super early game, they're more cost effective than regular cursed earth farms. More spawns occur and more exp is received. The demographic that uses these farms will just move onto a better alternative. Either way, mod farms come built-in with a punishment feature: the difficulty scaling. The cost of getting so much exp is the chance that the mobs that spawn will hit much harder and kill the player more often.

Perhaps we removed the fans involved in cursed earth farms? We could make cursed earth killing rooms at our disposal with lapis lights. A not brain dead approach to using cursed earth which allows players to get at least some exp and mob spawn specific drops as well.

**Comment by DoctorMage** [comment]
I would say leave it or if your going to go for the nuclear option just lock it behind a quest
Currently endermen farms dont work due to watcher spawns

Using cursed earth has downsides
Faster difficulty increase
Takes a while to setup if you include fans
Mob spawns are depedant on location

While i'm against cursed earth farms and find it boring disabling it is just going to lead to complaints 
balance wise it fits in with the rest of rad if players really watned to there are farming methods that are better than cursed earth 
Their are also benefical drops from it

**Comment by Zarchyar** [comment]
I know I tend to use cursed earth specificly for thaumcraft and getting generic mob drops. 
 
Id say it might be worth locking it to be only gotten via quest or say custom loot table injection.

**Comment by SamaraIsnt** [comment]
Nah![image](https://github.com/SamaraIsnt/Roguelike-Adventures-and-Dungeons/assets/104589186/e5eacdde-d79e-439c-a022-aaab9219b59b)
