### ISSUE TITLE
SUGGESTION: Add ContentTweaker and LootTweaker

### ISSUE THREAD

**Issue by Zarchyar** [SamaraIsnt/RADRevampProject#364]
ContentTweaker and dependency - used to create new fluids blocks ext (also for some additional functions)
https://www.curseforge.com/minecraft/mc-mods/contenttweaker
https://www.curseforge.com/minecraft/mc-mods/base

LootTweaker - used to modify loot tables via craft tweeker
https://www.curseforge.com/minecraft/mc-mods/loottweaker

**Comment by dr3ams** [comment]
Done for 1.52
