### ISSUE TITLE
Quest Suggestion

### ISSUE THREAD

**Issue by DoctorMage** [SamaraIsnt/RADRevampProject#371]
Tropicraft add a warning about the portals size and it breaking base blocks same with betweenlands tree

Powered diamond anvil suggestion of looted spectre coil

Remove this
![image](https://user-images.githubusercontent.com/85318453/190276837-5720f62d-b0ad-4570-bbc0-1127bbdf44e5.png)

**Comment by SamaraIsnt** [comment]
Second and third issue addressed in my most recent merge (10/7/2022) but could you explain more about the Tropicraft portals?

**Comment by DoctorMage** [comment]
https://streamable.com/lc1byc

> Second and third issue addressed in my most recent merge (10/7/2022) but could you explain more about the Tropicraft portals?
