### ISSUE TITLE
Update Broke Corail Tombstone

### ISSUE THREAD

**Issue by JonySnowball** [SamaraIsnt/RADRevampProject#374]
1. 1.52 
2. After the update, decorative tombstones stopped working in my old world, souls arrive, but books mostly do nothing if they are used on a tombstone. Also, tombstones are now impossible to break, they drop out, but remain in place, although I have been crafting and building from after the update. Everything worked fine before the update.
3. Create a world on 1.51 -> Upgrade from 1.51 to 1.52 -> build a decorative tombstone -> wait for the soul -> use the book of disenchantment with some enchanted object for example and try to break a tombstone

**Comment by DoctorMage** [comment]
Test this with just corail tombstone as the mod wdas updated
Aka create a solo instance with just corail that was in 1.51 rad do the test tehn update corial and see if its repeatable if it is
issue on corails end and needs to be reported to there github

**Comment by DoctorMage** [comment]
fixed via updating corail or making graves unbreakable in config
Corail31/tombstone_lite/issues/93
