### ISSUE TITLE
[Quest Bug] The Most Illusive Libary

### ISSUE THREAD

**Issue by SamaraIsnt** [SamaraIsnt/RADRevampProject#409]
# Quest Bug Report

**What version of RAD are you playing?**
1.53
___

**Name of bugged quest**
The Most Illusive Libary 
**Name of the quest tab the bugged quest is in**
Diggy Diggy Hole
**Describe the issue with the bugged quest**
Block Observation will not trigger completion. Also misspelling of "Lib**r**ary" in title and description.
(optional) **Screenshot**

**Comment by DoctorMage** [comment]
fixed in #414
