### ISSUE TITLE
[Bug] Server files give a more up to date RADENCHANTS jar then the client.

### ISSUE THREAD

**Issue by Zilacon** [SamaraIsnt/RADRevampProject#422]
# Bug Report

**What version of RAD are you playing?**
1.54

**Which launcher are you playing RAD on?**
Curseforge

**Have you added any mods? If yes, list them (includes Optifine)**
No

**Describe the bug**
Client has RADEnchants 1.0.0 but the server files gives RADEnchants 1.0.1a causing a mod conflict when joining the server.

**Steps to recreate**
Use the server files download from curseforge to start a server, use a install of 1.54 on curseforge client to connect, get a mod conflict.

**Attached crash log or latest.log** ***DO NOT COPY PASTE***
[08:49:09] [Netty Epoll Server IO #1/INFO]: Rejecting connection CLIENT: Rad Enchants: Requires version 1.0.1a-BETA but client has 1.0.0-BETA.
[08:49:09] [Netty Epoll Server IO #1/ERROR]: Network Disconnect: Server Mod rejections:
Rad Enchants: Requires version 1.0.1a-BETA but client has 1.0.0-BETA.                                                                                                                        
[08:49:09] [Server thread/INFO]: ZilaconMC lost connection: Server Mod rejections:
Rad Enchants: Requires version 1.0.1a-BETA but client has 1.0.0-BETA.

**Comment by DoctorMage** [comment]
![image](https://github.com/DoctorMage/Roguelike-Adventures-and-Dungeons/assets/85318453/c69b6dd9-592a-44ab-912e-0de116b5ee74)
![image](https://github.com/DoctorMage/Roguelike-Adventures-and-Dungeons/assets/85318453/f72fa56f-3161-4d10-9ee8-896d9842ddfb)
are you downloading the server pack from the website or the application

**Comment by Zilacon** [comment]
I downloaded it from here: https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons/files/4747839

**Comment by DoctorMage** [comment]
downloaded it from same link and its still  RADEnchants 1.0.0
just replace the one on the server with the client one 

seems like a curseforge bug

**Comment by Zilacon** [comment]
Yeah ive already rolled it back to 1.0.0, just figured id report it here as im unsure if there was any major issues fixed in the updated version.

**Comment by DoctorMage** [comment]
rad enchants 1.0.1 had issues with the bewteenlands so it was revereted to an older version
